In [1]:
%pip install -r ../requirements.txt

Requirement already satisfied: python-dotenv in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from -r ../requirements.txt (line 2)) (1.2.3)
Requirement already satisfied: pandas in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from -r ../requirements.txt (line 5)) (3.0.6)
Requirement already satisfied: numpy in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from -r ../requirements.txt (line 6)) (2.5.3)
Requirement already satisfied: openpyxl in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from -r ../requirements.txt (line 7)) (3.1.5)
Collecting scikit-learn (from -r ../requirements.txt (line 8))
  Downloading scikit_learn-1.9.1-cp313-cp313-macosx_12_0_arm64.whl.metadata (9.3 kB)
Requirement already satisfied: matplotlib in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from -r ../requirements.txt (line 11)) (3.11.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /Users/monicabarbosa/Library/Python/3.13/lib/python/site-packages (from pandas->-r ../requirements.txt (line 5)) (2.9.0.post0)
Requirement already satisfied: et-xmlfile in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from openpyxl->-r ../requirements.txt (line 7)) (2.0.0)
Collecting scipy>=1.10.0 (from scikit-learn->-r ../requirements.txt (line 8))
  Downloading scipy-1.18.1-cp313-cp313-macosx_14_0_arm64.whl.metadata (62 kB)
Collecting joblib>=1.4.0 (from scikit-learn->-r ../requirements.txt (line 8))
  Using cached joblib-1.6.0-py3-none-any.whl.metadata (6.5 kB)
Collecting narwhals>=2.0.1 (from scikit-learn->-r ../requirements.txt (line 8))
  Downloading narwhals-2.26.0-py3-none-any.whl.metadata (15 kB)
Collecting threadpoolctl>=3.5.0 (from scikit-learn->-r ../requirements.txt (line 8))
  Using cached threadpoolctl-3.7.0-py3-none-any.whl.metadata (24 kB)
Requirement already satisfied: contourpy>=1.0.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib->-r ../requirements.txt (line 11)) (1.4.0)
Requirement already satisfied: cycler>=0.10 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib->-r ../requirements.txt (line 11)) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib->-r ../requirements.txt (line 11)) (4.66.0)
Requirement already satisfied: kiwisolver>=1.3.1 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib->-r ../requirements.txt (line 11)) (1.5.1)
Requirement already satisfied: packaging>=20.0 in /Users/monicabarbosa/Library/Python/3.13/lib/python/site-packages (from matplotlib->-r ../requirements.txt (line 11)) (26.3)
Requirement already satisfied: pillow>=9 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib->-r ../requirements.txt (line 11)) (12.3.0)
Requirement already satisfied: pyparsing>=3 in /Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages (from matplotlib->-r ../requirements.txt (line 11)) (3.3.3)
Collecting cloudpickle>=3.0 (from joblib>=1.4.0->scikit-learn->-r ../requirements.txt (line 8))
  Using cached cloudpickle-3.1.2-py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: six>=1.5 in /Users/monicabarbosa/Library/Python/3.13/lib/python/site-packages (from python-dateutil>=2.8.2->pandas->-r ../requirements.txt (line 5)) (1.17.0)
Downloading scikit_learn-1.9.1-cp313-cp313-macosx_12_0_arm64.whl (8.3 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.3/8.3 MB 10.6 MB/s eta 0:00:00a 0:00:01
Using cached joblib-1.6.0-py3-none-any.whl (306 kB)
Downloading narwhals-2.26.0-py3-none-any.whl (474 kB)
Downloading scipy-1.18.1-cp313-cp313-macosx_14_0_arm64.whl (20.5 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 20.5/20.5 MB 9.8 MB/s eta 0:00:0000:0100:01
Using cached threadpoolctl-3.7.0-py3-none-any.whl (26 kB)
Using cached cloudpickle-3.1.2-py3-none-any.whl (22 kB)
Installing collected packages: threadpoolctl, scipy, narwhals, cloudpickle, joblib, scikit-learn
Successfully installed cloudpickle-3.1.2 joblib-1.6.0 narwhals-2.26.0 scikit-learn-1.9.1 scipy-1.18.1 threadpoolctl-3.7.0

[notice] A new release of pip is available: 24.2 -> 26.2.1
[notice] To update, run: pip3 install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [6]:
projects = pd.read_csv("../Watts_Happening/data/projects.csv")
overlaps = pd.read_csv("../Watts_Happening/data/overlaps.csv")

projects.head()

,project_id,utility,state,project_name,name_a,lat_a,lon_a,name_b,lat_b,lon_b,lat_center,lon_center,in_service_date,cost,Unnamed: 14,Unnamed: 15,Unnamed: 16
0,DESC_1,Dominion Energy South Carolina,SC,Stevens Creek - Hooks 115 kV / LR Plumb Branch...,Stevens Creek Sub,33.562599,-82.051362,Hooks Sub,NaN,NaN,33.562599,-82.051362,12/31/2024,NaN,NaN,NaN,NaN
1,DESC_2,Dominion Energy South Carolina,SC,Hooks - Thurmond 115 kV Tie: Rebuild,Hooks Sub,NaN,NaN,Thurmond Sub,33.660127,-82.195931,33.660127,-82.195931,12/31/2024,NaN,NaN,NaN,NaN
2,DESC_3,Dominion Energy South Carolina,SC,Jasper - Okatie 230 kV #2: Construct,Jasper Sub,32.359120,-81.124600,Okatie Sub,32.333758,-81.032495,32.346439,-81.078547,12/31/2025,NaN,NaN,NaN,NaN
3,DESC_4,Dominion Energy South Carolina,SC,Queensboro - Ft Johnson 115 kV & Queensboro-Ba...,Queensboro Sub,32.722793,-79.967332,Ft Johnson Sub,NaN,NaN,32.722793,-79.967332,12/31/2023,NaN,NaN,NaN,NaN
4,DESC_5,Dominion Energy South Carolina,SC,Okatie-Bluffton 115 kV: Rebuild,Okatie Sub,32.333758,-81.032495,Bluffton Sub,32.235027,-80.853384,32.284393,-80.942939,2025/6/1,NaN,NaN,NaN,NaN

In [8]:
overlaps.head()

,overlap_id,distance_mi,time_gap (day),utility_a,project_id_a,project_name_a,utility_b,project_id_b,project_name_b
0,OVL_1,4.09,3074,Dominion Energy South Carolina,DESC_2,Hooks - Thurmond 115 kV Tie: Rebuild,Georgia Power,GPC_1,EVANS PRIMARY - THURMOND DAM (USA) #5 115KV RE...
1,OVL_2,5.65,152,Dominion Energy South Carolina,DESC_3,Jasper - Okatie 230 kV #2: Construct,Georgia Power,GPC_2,SAV: MCINTOSH - PURRYSBURG 230KV REACTORS
2,OVL_3,7.55,517,Dominion Energy South Carolina,DESC_3,Jasper - Okatie 230 kV #2: Construct,Georgia Power,GPC_3,SAV: GOSHEN (SAV) - MCINTOSH 115KV LINE REBUILD
3,OVL_4,8.01,3074,Dominion Energy South Carolina,DESC_1,Stevens Creek - Hooks 115 kV / LR Plumb Branch...,Georgia Power,GPC_1,EVANS PRIMARY - THURMOND DAM (USA) #5 115KV RE...
4,OVL_5,14.34,365,Dominion Energy South Carolina,DESC_5,Okatie-Bluffton 115 kV: Rebuild,Georgia Power,GPC_2,SAV: MCINTOSH - PURRYSBURG 230KV REACTORS